### ISSUE TITLE
freeAuthMelissa lookup returns: freeauthMelissa is not in GOROOT (/usr/lib/go-1.17/src/freeauthMelissa)

### ISSUE THREAD

**Issue by apatheticposture** [ax-i-om/bitcrook#4]
I am unsure how/where to add this to GOROOT on my system.  I installed this via the instructions on the project page:

https://github.com/audioo/bitcrook

I am running the CLI version.

Would have expected this to be added via the go run main.go command where it installs dependencies.  The returned error message is looking for this outside of the directory tree where I install my github projects.

Currently, the melissa stuff is in: /home/apatheticposture/github/bitcrook/pkg/authfree/melissa

Is there a way to run this such that it does look in my main system directories, or a single command to copy this and anything else bitcrook expects to the expected GOROOT?

**Comment by audioo** [comment]
Hi there, just letting you know that I have seen and acknowledged your issue. Thank you for letting me know, and I will get back to you as soon as I have more time on my hands.

**Comment by ax-i-om** [comment]
Closed due to significant change to project structure. If you continue to experience this issue, feel free to open a new issue. Thanks!
